airbnb:
  outputs:
    dev:
      type: snowflake
      account: hpfzrnn-drb05159
      user: admin
      password: 'Password123'
      role: TRANSFORM
      warehouse: COMPUTE_WH
      database: AIRBNB
      schema: DEV
      threads: 1
  target: dev
